apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: eventsource-handler
spec:
  version: "v4.0.0"
  image: "openfunction/eventsource-handler:v4"
  imageCredentials:
    name: push-secret
  port: 8080
  build:
    builder: openfunction/builder-go:latest
    env:
      FUNC_NAME: "EventSourceHandler"
      FUNC_CLEAR_SOURCE: "true"
    srcRepo:
      url: "https://github.com/OpenFunction/events-handlers.git"
      sourceSubPath: "eventsource/function/v4"
